export const header = "border-solid border-1 border-grey-400 m-auto flex justify-between items-center w-full h-16 bg-transparent"
export const allBtn = "flex -mr-12"
export const navBtn = "bg-transparent border-transparent pl-5"
export const box = "bg-red-300 text-center border-transparent rounded -mr-48 h-8 text-red-700"
export const input = "w-64 h-8 bg-gray-200 border-transparent rounded"
export const info = "m-auto my-10"
export const section = "m-auto w-5/6 my-6 grid grid-cols-4 gap-6"
export const footer = "m-auto mt-12 w-full h-full pt-12 flex justify-around bg-black text-white"